# Generated by Django 2.0.7 on 2018-08-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=30)),
                ('sender', models.CharField(max_length=30)),
                ('tname', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('pubkey', models.CharField(max_length=30)),
                ('prevkey_file', models.CharField(max_length=50)),
            ],
        ),
    ]
